### ISSUE TITLE
Crash by loading a bookmark

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#273]
With master, loading a bookmark makes the app crashs.

**Comment by mhutti1** [comment]
@kelson42 For me it doesn't Can I have some more details/stack trace

**Comment by mhutti1** [comment]
@kelson42 Can you also try uninstalling the app and then installing because I think the database is in compatible with a certain commit and that could be the issue.

**Comment by kelson42** [comment]
Here is the crash I get by opening a bookmark

```
E/SELinux (19440): [DEBUG] get_category: variable seinfo: platform sensitivity: NULL, cateogry: NULL
W/cr_AwContents(19214): onDetachedFromWindow called when already detached. Ignoring
D/hwcutils( 2254): MppFactory::MppFactory()
D/        ( 2254): virtual LibMpp* MppFactory::CreateMpp(int, int, int, int) dev(5) mode(0) drm(0), 
D/libexynosgscaler( 2254): LibMpp::LibMpp()
I/cr_Ime  (19214): ImeThread is not enabled.
D/kiwix   (19214): mNightMode value (false)
D/kiwix   (19214):  Kiwix normal start, zimFile loaded last time -> Open last used zimFile /storage/emulated/0/Android/obb/org.kiwix.kiwixcustomwikivoyage/main.11.org.kiwix.kiwixcustomwikivoyage.obb
D/kiwix   (19214): mNightMode value (false)
D/kiwix   (19214): mNightMode value (false)
I/kiwix   (19214): Intent data: Intent { (has extras) }
W/ResourceType(19214): Failure getting entry for 0x01080acf (t=7 e=2767) (error -75)
W/cr_AwContents(19214): onDetachedFromWindow called when already detached. Ignoring
D/TimaKeyStoreProvider(19440): TimaSignature is unavailable
D/ActivityThread(19440): Added TimaKeyStore provider
I/cr_Ime  (19214): ImeThread is not enabled.
D/kiwix   (19214): mNightMode value (false)
D/AndroidRuntime(19214): Shutting down VM
E/AndroidRuntime(19214): FATAL EXCEPTION: main
E/AndroidRuntime(19214): Process: org.kiwix.kiwixcustomwikivoyage, PID: 19214
E/AndroidRuntime(19214): java.lang.RuntimeException: Unable to resume activity {org.kiwix.kiwixcustomwikivoyage/org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {org.kiwix.kiwixcustomwikivoyage/org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
E/AndroidRuntime(19214):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3509)
E/AndroidRuntime(19214):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3540)
E/AndroidRuntime(19214):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2860)
E/AndroidRuntime(19214):    at android.app.ActivityThread.access$900(ActivityThread.java:181)
E/AndroidRuntime(19214):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
E/AndroidRuntime(19214):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19214):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(19214):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime(19214):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19214):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19214):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(19214):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/AndroidRuntime(19214): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {org.kiwix.kiwixcustomwikivoyage/org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
E/AndroidRuntime(19214):    at android.app.ActivityThread.deliverResults(ActivityThread.java:4173)
E/AndroidRuntime(19214):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3495)
E/AndroidRuntime(19214):    ... 11 more
E/AndroidRuntime(19214): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
E/AndroidRuntime(19214):    at org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity.refreshBookmarkSymbol(KiwixMobileActivity.java:1403)
E/AndroidRuntime(19214):    at org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity.onActivityResult(KiwixMobileActivity.java:1364)
E/AndroidRuntime(19214):    at android.app.Activity.dispatchActivityResult(Activity.java:6632)
E/AndroidRuntime(19214):    at android.app.ActivityThread.deliverResults(ActivityThread.java:4169)
E/AndroidRuntime(19214):    ... 12 more
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixcustomwikivoyage
W/ActivityManager( 2800):   Force finishing activity org.kiwix.kiwixcustomwikivoyage/.KiwixMobileActivity
D/FocusedStackFrame( 2800): Set to : 0
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixcustomwikivoyage
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname com.sec.android.app.launcher
D/libexynosgscaler( 2254): virtual CGscaler::~CGscaler()
D/libexynosgscaler( 2254): virtual LibMpp::~LibMpp()
D/        ( 2254): virtual MppFactory::~MppFactory()

```

**Comment by kelson42** [comment]
Now it seems to be even more broken than before, it can not stop crashing. Here with a dev version of Kiwix

```
E/AndroidRuntime(13281): Process: org.kiwix.kiwixmobile, PID: 13281
E/AndroidRuntime(13281): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
E/AndroidRuntime(13281):    at org.kiwix.kiwixmobile.KiwixMobileActivity.refreshBookmarkSymbol(KiwixMobileActivity.java:1411)
E/AndroidRuntime(13281):    at org.kiwix.kiwixmobile.KiwixMobileActivity.onPrepareOptionsMenu(KiwixMobileActivity.java:1400)
E/AndroidRuntime(13281):    at android.app.Activity.onPreparePanel(Activity.java:2982)
E/AndroidRuntime(13281):    at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:547)
E/AndroidRuntime(13281):    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:536)
E/AndroidRuntime(13281):    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
E/AndroidRuntime(13281):    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
E/AndroidRuntime(13281):    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
E/AndroidRuntime(13281):    at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
E/AndroidRuntime(13281):    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
E/AndroidRuntime(13281):    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
E/AndroidRuntime(13281):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
E/AndroidRuntime(13281):    at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime(13281):    at android.view.Choreographer.doFrame(Choreographer.java:559)
E/AndroidRuntime(13281):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/AndroidRuntime(13281):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(13281):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(13281):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(13281):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime(13281):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13281):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13281):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(13281):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
W/ActivityManager( 2800):   Force finishing activity org.kiwix.kiwixmobile/.KiwixMobileActivity
D/FocusedStackFrame( 2800): Set to : 0
```

**Comment by mhutti1** [comment]
Again this seems to be an issue with code not being called in the right order. We moved the bookmarking code further down in the on create method. Its still in the method. But turns out different things are called at different times on different devices. It looks like its not getting round to initialising the bookmark code before its needed. I think I have fixed.

**Comment by kelson42** [comment]
Still dies :( To me it sounds a pretty classical problem which should have a classical answer.

```
kiwix   (28987): Getting mime-type for content://org.kiwix.zim.base/A/index.htm = text/html
W/ContextImpl( 2800): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1700 com.android.server.InputMethodManagerService$6.run:2765 java.lang.Thread.run:818 <bottom of call stack> <bottom of call stack> 
D/kiwix   (28987): Loading article finished.
D/kiwix   (28987): Loaded URL: null
D/AndroidRuntime(28987): Shutting down VM
E/AndroidRuntime(28987): FATAL EXCEPTION: main
E/AndroidRuntime(28987): Process: org.kiwix.kiwixmobile, PID: 28987
E/AndroidRuntime(28987): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
E/AndroidRuntime(28987):    at org.kiwix.kiwixmobile.KiwixMobileActivity.refreshBookmarkSymbol(KiwixMobileActivity.java:1411)
E/AndroidRuntime(28987):    at org.kiwix.kiwixmobile.KiwixMobileActivity.onPrepareOptionsMenu(KiwixMobileActivity.java:1400)
E/AndroidRuntime(28987):    at android.app.Activity.onPreparePanel(Activity.java:2982)
E/AndroidRuntime(28987):    at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:547)
E/AndroidRuntime(28987):    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:536)
E/AndroidRuntime(28987):    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
E/AndroidRuntime(28987):    at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
E/AndroidRuntime(28987):    at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
E/AndroidRuntime(28987):    at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
E/AndroidRuntime(28987):    at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
E/AndroidRuntime(28987):    at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
E/AndroidRuntime(28987):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
E/AndroidRuntime(28987):    at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime(28987):    at android.view.Choreographer.doFrame(Choreographer.java:559)
E/AndroidRuntime(28987):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/AndroidRuntime(28987):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(28987):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28987):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(28987):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime(28987):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28987):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28987):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime(28987):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
I/art     (29226): System.exit called, status: 0
I/AndroidRuntime(29226): VM exiting with result code 0, cleanup skipped.
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
W/ActivityManager( 2800):   Force finishing activity org.kiwix.kiwixmobile/.KiwixMobileActivity
D/FocusedStackFrame( 2800): Set to : 0
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname com.sec.android.app.launcher
```

**Comment by mhutti1** [comment]
@kelson42. Your new stacktrace shows the same line causing the issue. That can't be right. You haven't updated the app properly. There is no ArrayList.contains on that line.

**Comment by kelson42** [comment]
@mhutti1 Yes, sorry you are right. It works better but it still crash by opening a specific bookmark (relaod bookmarked page)

```
D/kiwix   ( 9976): mNightMode value (false)
D/kiwix   ( 9976):  Kiwix normal start, zimFile loaded last time -> Open last used zimFile /mnt/sdcard/Documents/vikidia_fr_all_20'15-11.zim
D/kiwix   ( 9976): mNightMode value (false)
D/kiwix   ( 9976): mNightMode value (false)
D/TimaKeyStoreProvider(10242): TimaSignature is unavailable
D/ActivityThread(10242): Added TimaKeyStore provider
I/kiwix   ( 9976): Intent data: Intent { (has extras) }
W/ResourceType( 9976): Failure getting entry for 0x01080acf (t=7 e=2767) (error -75)
W/cr_AwContents( 9976): onDetachedFromWindow called when already detached. Ignoring
I/cr_Ime  ( 9976): ImeThread is not enabled.
D/kiwix   ( 9976): mNightMode value (false)
D/AndroidRuntime( 9976): Shutting down VM
E/AndroidRuntime( 9976): FATAL EXCEPTION: main
E/AndroidRuntime( 9976): Process: org.kiwix.kiwixmobile, PID: 9976
E/AndroidRuntime( 9976): java.lang.RuntimeException: Unable to resume activity {org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
E/AndroidRuntime( 9976):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3509)
E/AndroidRuntime( 9976):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3540)
E/AndroidRuntime( 9976):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2860)
E/AndroidRuntime( 9976):    at android.app.ActivityThread.access$900(ActivityThread.java:181)
E/AndroidRuntime( 9976):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
E/AndroidRuntime( 9976):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9976):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 9976):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime( 9976):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9976):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9976):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 9976):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/AndroidRuntime( 9976): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { (has extras) }} to activity {org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
E/AndroidRuntime( 9976):    at android.app.ActivityThread.deliverResults(ActivityThread.java:4173)
E/AndroidRuntime( 9976):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3495)
E/AndroidRuntime( 9976):    ... 11 more
E/AndroidRuntime( 9976): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.Menu.findItem(int)' on a null object reference
E/AndroidRuntime( 9976):    at org.kiwix.kiwixmobile.KiwixMobileActivity.refreshBookmarkSymbol(KiwixMobileActivity.java:1410)
E/AndroidRuntime( 9976):    at org.kiwix.kiwixmobile.KiwixMobileActivity.onActivityResult(KiwixMobileActivity.java:1367)
E/AndroidRuntime( 9976):    at android.app.Activity.dispatchActivityResult(Activity.java:6632)
E/AndroidRuntime( 9976):    at android.app.ActivityThread.deliverResults(ActivityThread.java:4169)
E/AndroidRuntime( 9976):    ... 12 more
V/ApplicationPolicy( 2800): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
W/ActivityManager( 2800):   Force finishing activity org.kiwix.kiwixmobile/.KiwixMobileActivity

```

**Comment by mhutti1** [comment]
@kelson42 How about this?

**Comment by kelson42** [comment]
@mhutti1 FIXED :))) THX
